### ISSUE TITLE
releasing a tag as draft does not properly work

### ISSUE THREAD

**Issue by Vampire** [wooga/atlas-github#18]
The line `release.update().draft(isDraft()).update()` corrupts the release tag.
Before the line (breakpoint on the line):
![grafik](https://user-images.githubusercontent.com/325196/39575653-9fe7d624-4edb-11e8-95b4-5e7b53fd3fa1.png)
After the line (stepped over)
![grafik](https://user-images.githubusercontent.com/325196/39575710-cdf2263c-4edb-11e8-9c02-b4ac25e5db40.png)
Which will result in a new tag called `untagged-4b7ab7ff233227717a2d` on the current `master` commit instead of on the tag when the release is published without fixing it first.

**Comment by Vampire** [comment]
And to be more specific, it is the last `.update()` call that breaks it.

**Comment by Vampire** [comment]
While switching the draft state should not break the release, actually the whole call is unnecessary here, as the release is already in draft state actually.

**Comment by Vampire** [comment]
I'd say this is a bug in GitHub actually, if I use HTTPie it is the same.
If I patch the release to `draft=true` it sometimes changes the tag name to `untagged-<whatever>`.
Would you mind releasing a version with `release.update().draft(isDraft()).update()` replaced by `release.update().draft(isDraft()).tag(getTagName()).update()` soon, or even better `if (release.draft != isDraft()) { release.update().draft(isDraft()).tag(getTagName()).update() }`, as an unnecessary call is prevented then.

I made PR #19 that fixes this and while I was at it also #17.

Would be nice if you could release that soon, as I cannot finish the PR I'm preparing with your plugin if this doesn't work properly.

**Comment by Larusso** [comment]
see https://github.com/wooga/atlas-github/releases/tag/v1.0.1
