### ISSUE TITLE
Plugin is not usable from Kotlin build script

### ISSUE THREAD

**Issue by Vampire** [wooga/atlas-github#28]
See here for detailed information: https://github.com/gradle/gradle/issues/9003
I guess this is a Gradle bug, but using the convention mechanism is obsolete anyways, so to fix it on your side, you could change your plugin to use the extensions mechanism instead which should work better and is recommended.

**Comment by Larusso** [comment]
Well I don’t support Gradle 5 to begin with. I had no time looking into it at the moment. 

What extension mechanism are you referring to? The only other API that support lazy configuration is the Provider API which is in Incubation.

**Comment by Vampire** [comment]
I guess this is not different in Gradle 4.10.3 either.
I'm referring to **the** extensions mechanism that is to replace conventions mid-term.
Here an example: https://github.com/gradle/gradle/pull/5867/files
And here according documentation: https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build

**Comment by Larusso** [comment]
The docs link to the ProviderAPI.
I use extensions in this plugin. But choose to you the internal mapping solution instead of fetching the extension in the task implementation. 

https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_configuration

**Comment by Vampire** [comment]
Well, then maybe that's the way to go?
Or if you don't want to use it, I don't know, get and use the extension in your task implementation?
I'm not too deep into plugin writing with lazy configuration.
I just know that the convention mechanism is deprecated and will eventually go and that it obviously doesn't work properly from Kotlin DSL.

**Comment by Larusso** [comment]
I started to use the Provider API in a few other plugins. But as this one is a moving target as well I opted for now to stick to the ConventionMapping.  I'm really torn here. My IDE ether warns me that something is deprecated/internal or incubating :)
Let me check if I can write a test with a kotlin build script that triggers this issue.

**Comment by Vampire** [comment]
Should be easy, set the repository name and see whether it was skipped for example.

**Comment by Larusso** [comment]
By any chance did you try to set the repository in the extension?

*build.gradle*
```groovy
plugins {
    id 'net.wooga.github' version '1.3.0'
}

github {
    repositoryName "..."
}

```

Because this is where the convention mapping falls back to.
If of course you want multiple publish tasks with different repos this won't help you.

**Comment by Vampire** [comment]
That could help if the issue were restricted to the repository name, but I also set the tag name, release name and draft property which are all not settable in the extension which is why I simply did all config in the task directly as I had to configure it anyway.

**Comment by Larusso** [comment]
Ok that makes sense. I wonder how this impacts internal tasks from Gradle. Because some still use convention mapping.

**Comment by Vampire** [comment]
Excellent question, but I have no idea, yours is the first one I found failing.

**Comment by Larusso** [comment]
Hmm it seems that Testkit also has still some issues with the Kotlin DSL:
```
* What went wrong:
java.lang.ExceptionInInitializerError (no error message)
> Type org.gradle.api.tasks.SourceSet not present

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.ExceptionInInitializerError
	at org.gradle.kotlin.dsl.provider.plugins.DefaultProjectSchemaProvider.schemaFor(DefaultProjectSchemaProvider.kt:35)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.schemaFor(AccessorsClassPath.kt:127)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.jitProjectSchemaOf(AccessorsClassPath.kt:104)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.configuredProjectSchemaOf(AccessorsClassPath.kt:86)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.buildAccessorsClassPathFor(AccessorsClassPath.kt:72)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.access$buildAccessorsClassPathFor(AccessorsClassPath.kt:1)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.accessorsClassPathFor(AccessorsClassPath.kt:58)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.accessorsClassPathFor(Interpreter.kt:418)
	at Program.execute(Unknown Source)
```

https://github.com/gradle/kotlin-dsl/issues/1261

**Comment by Vampire** [comment]
And if you disable withDebug like mentioned?

**Comment by Larusso** [comment]
So it works for me in gradle `4.10`

I execute this test build:

```kotlin
plugins {
    id("net.wooga.github") version "1.3.0"
}

version = "0.3.851-GithubPublishPropertySpec"

tasks.register<wooga.gradle.github.publish.tasks.GithubPublish>("testPublish") {
    isDraft = false
    tagName = "v0.3.851-GithubPublishPropertySpec"
    repositoryName = "larusso/..."
    token = "..."
}
```

I will see what happens when I use Gradle 5

**Comment by Larusso** [comment]
Ok.

Gradle `5.3`, `5.2` fails.
Gradle `5.1` works for me. So it looks like a regression.

```
> Task :testPublish SKIPPED
Skipping task ':testPublish' as task onlyIf is false.
:testPublish (Thread[Daemon worker,5,main]) completed. Took 0.026 secs.
```

**Comment by Larusso** [comment]
Apart from this I will check if I have time to move this plugin to the Provider API. It is fairly small.

**Comment by Vampire** [comment]
A little side question if you may allow, your release notes plugin is incompatible with the researchgate release plugin?
I have that applied and now wanted to try your release notes plugin, but it fails trying to register `release` extension a second time.

**Comment by Vampire** [comment]
Hm, forget it, this seems to also depend on the deprecated gradle-git plugin which then complains that no version stragies are defined after I removed the release plugin for testing, I don't like where this moves to. :-D

**Comment by Larusso** [comment]
Yeah I have fun times ahead. The release notes plugin is also very opinionated towards our internal usage. We want to create something in the coming days that is less overloaded.

**Comment by Larusso** [comment]
I created a new major line `release/2.x` and published a candidate build.
```
plugins {
  id("net.wooga.github") version "2.0.0-rc.1"
}
```

I had no time to test this against gradle 5 and the Kotlin DSL. If you have time could you take a spin with this version?

**Comment by Vampire** [comment]
Looks better in regard of this issue report.
Just the syntax becomes a bit awkward with the provider stuff, you always have to call `set(...)`.
You could add methods that do this for you, like having a `draft(boolean draft)` method that calls `this.draft.set(draft)`, then instead of having to do `draft.set(true)`, one could do `draft(true)`.

Hm, actually I can also use operator overloading to achieve that, but it is probably better / more convenient for all users to provide this out of the box:

```java
operator fun <T> Property<T>.remAssign(value: T) = set(value)
operator fun <T> Property<T>.divAssign(value: T) = set(value)
operator fun <T> Property<T>.timesAssign(value: T) = set(value)
operator fun <T> Property<T>.invoke(value: T) = set(value)

tasks.githubPublish {
    prerelease.set(true)
    repositoryName %= githubRepositoryName
    tagName /= releaseTagName
    releaseName *= releaseTagName
    draft(true)
}
```

**Comment by Larusso** [comment]
They implemented this automatic conversion between `prerelease = true` to `prerelease.set(true)` in the groovy DSL. 
And I still provide the old set methods:

https://github.com/wooga/atlas-github/blob/release/2.x/src/main/groovy/wooga/gradle/github/base/GithubSpec.groovy

https://github.com/wooga/atlas-github/blob/release/2.x/src/main/groovy/wooga/gradle/github/publish/GithubPublishSpec.groovy

I personally don't know how Kotlin DSL works here.

**Comment by Vampire** [comment]
Oh, damn, now I feel blind and very sorry.
It is great you provide those methods, please keep them.
And with those, it even works in 1.3.0 as then the Groovy code sets the value which seems to do the necessary bit that is not done if you assign the value from the Kotlin DSL.

**Comment by Larusso** [comment]
Ah good to know.
I personally like the new Provider API but it feels still clunky in some areas because Java is not Haskell :)
I think I will still move to this API but might need to add a better test support for Kotlin.

**Comment by Larusso** [comment]
Is this issue solved with either `2.x` or the usage of the special set methods?

**Comment by Vampire** [comment]
Umh, yes, I think so.
At least that is what I wrote above.
And I also removed the workaround I had in place, so I guess, yes. :-D
