### ISSUE TITLE
PublishBodyStrategy is invoked multiple times

### ISSUE THREAD

**Issue by Vampire** [wooga/atlas-github#31]
If you execute the `githubPublish` task and configured a `PublishBodyStrategy`, it is called three times.
Please call it only once and cache the value, the calculation could be relatively heavy (involving remote calls, git repository inspection and so on) and shouldn't be necessary multiple times.

Workaround is to use a lazy property yourself to cache the value, for example in Kotlin with a lazy delegate.

**Comment by Larusso** [comment]
@Vampire ah you are right. These `Provider` objects are by nature like this. I will write a test and see to evaluate it once per task execution/access

**Comment by Vampire** [comment]
Just to clarify, no didn't yet test the new rc, the issues I just opened are with the stable version.

**Comment by Larusso** [comment]
So I created a fix for the mainline and will also fix it for the new `Provider` based implementation

**Comment by Larusso** [comment]
Fixed in #32 and for in #33 for `2.x`.
