### ISSUE TITLE
Deprecations in Gradle 6 (will fail in Gradle 7)

### ISSUE THREAD

**Issue by Vampire** [wooga/atlas-github#55]
There are serveral deprecation warnings coming from your plugin if used with Gradle 6, what I have seen so far was mostly that your task properties are not annotated with input or output annotations. This will fail starting with Gradle 7.

**Comment by Larusso** [comment]
Thanks. I will take a look what I can do.

**Comment by Larusso** [comment]
the latest rc should fix these issues. I will make a full new release in a few hours if nothing gets in between.

**Comment by Vampire** [comment]
Time has gone, but release didn't come. :-(
When can we expect the final release?
Are there any blockers in the latest rc?

**Comment by Vampire** [comment]
Oh yes, there is a blocker still.
Even 2.0.0-rc.6 is not compatible with Gradle 7.
`GithubPublish.destinationDir`, `GithubPublish.excludes`, and `GithubPublish.includes` are missing input / output annotations.

Can you please reopen this issue or better right away fix it and create a new RC?

**Comment by Larusso** [comment]
@Vampire we have issues with the test suite and the github api. We run multiple plugins and upgraded all to be developed with the latest gradle 6 version about 6 month ago. The release just fell through.

**Comment by Larusso** [comment]
Ok. I did the fix and I was able to release the proper 2.0.0 finally. If you have any more issues just ring me up ;)
