### ISSUE TITLE
getRepositoryNameFromLocalGit fails working properly when not a GitHub URL

### ISSUE THREAD

**Issue by Vampire** [wooga/atlas-github#99]
In 2.0.0-rc.6 now the ability to determine the github repository was added.
But this only works properly if the `origin` remote has a `github.com` URL.
For any other URL, the `indexOf` returns `-1` and then a `substring(10)` is done.
Instead if it is not a GitHub URL, the property should have no value.

**Comment by Joaquimmnetto** [comment]
Fix done in PR #101.

**Comment by Larusso** [comment]
released in [v2.0.1](https://github.com/wooga/atlas-github/releases/tag/v2.0.1)
